### PR TITLE
v2 initial work.

### PR DESCRIPTION
**Pull request by ejez**

### CODE REVIEW

**Comment by ejez** [comment]
You can try with:
```sh
quasar ext add @ejez/apollo
```

Before publishing to npm (under @quasar/apollo) make sure to generate the js files first:
```sh
node_modules/typescript/bin/tsc --skipLibCheck
```

**Comment by ejez** [comment]
I made the PR against dev branch, you can create a branch `v2` from it afterwards.

I suggest that we adjust the install instructions for v1 to `quasar ext add @quasar/apollo@^1.0.0-beta`

**Comment by smolinari** [comment]
Oops. That is what I meant. This will end up in the dev branch, if I merge it. @ejez 

Let me figure out how to get the branch added, then you can redo the PR to that branch. Ok?

Scott

**Comment by ejez** [comment]
We can also make dev track v2, quasar v2 is mostly stable, what do you think?

**Comment by ejez** [comment]
Just to make sure... you noticed it, the new code is on github not gitlab
https://github.com/ejez/app-extension-apollo/tree/v2

**Comment by smolinari** [comment]
@ejez - If you could, re-PR to the v2 branch. 

I'd like to keep v2 in its own branch with v1 in dev and master until v2 of Quasar goes to final. At that point, I'll swap out v2 to dev and master and move v1 to its own branch. Sound ok?

Scott

**Pull request closed without merging**
